### ISSUE TITLE
belongsToMany relationship

### ISSUE THREAD

**Issue by wurin7i** [october-widgets/library#3]
Sorry, this is repost issue that previously sent on october-widgets/hasmany.

So, is it possible to use hasmany widget for belongsToMany relationship?
Thanks

**Comment by scottbedard** [comment]
Sorry, for now this widget only supports BelongsTo -> HasMany relationships. For a BelongsToMany, I recommend using a RelationController. You can watch a screencast demonstrating how to do this at https://vimeo.com/123489421
