### ISSUE TITLE
Invalid argument supplied for foreach line 78

### ISSUE THREAD

**Issue by that0n3guy** [october-widgets/library#5]
This is caused by pre-existing data in the database for a field... if `$loadValue` (https://github.com/october-widgets/tagbox/blob/master/Widget.php#L77) is null.

Should probably do a check `if($loadValue)` first.

```
Invalid argument supplied for foreach()
C:\xamppPHP55\htdocs\oca-forms\plugins\oca\webforms\vendor\owl\tagbox\Widget.php line 78
```

**Comment by scottbedard** [comment]
Good catch, thanks!
